#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const repoRoot = new URL('../..', import.meta.url).pathname;
const sourcePath = join(repoRoot, 'docs/api/openapi.json');
const outputRoot = getArg('--out') || join(repoRoot, 'docs/api');
const wikiOutputPath = getArg('--wiki-out') || join(repoRoot, 'docs/wiki/Reference/API-Reference.md');

const spec = JSON.parse(readFileSync(sourcePath, 'utf8'));

validateSpec(spec);

const outputs = new Map([
  [join(outputRoot, 'openapi.json'), `${JSON.stringify(spec, null, 2)}\n`],
  [join(outputRoot, 'openapi.yaml'), toYAML(spec)],
  [join(outputRoot, 'generated/API-Reference.md'), apiReference(spec)],
  [join(outputRoot, 'generated/Endpoints.md'), endpointsReference(spec)],
  [join(outputRoot, 'generated/Errors.md'), errorsReference(spec)]
]);

const wikiReference = apiReference(spec, {
  endpointsLink: '../../api/generated/Endpoints.md',
  errorsLink: '../../api/generated/Errors.md'
}).replace(
  '# Koji API Reference\n',
  '# API Reference\n\n[Home](../Home.md) | Related: [Request Flow](../Architecture/Request-Flow.md), [Capability Reference](Capability-Reference.md), [Error Code Reference](Error-Code-Reference.md)\n\n'
);
outputs.set(wikiOutputPath, wikiReference);

for (const [path, content] of outputs) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function validateSpec(document) {
  if (document.openapi !== '3.1.0') {
    throw new Error('OpenAPI version must be 3.1.0');
  }
  if (!document.info?.title || !document.info?.version) {
    throw new Error('OpenAPI info title and version are required');
  }
  for (const operation of operations(document)) {
    if (operation.operation['x-koji-auth-required'] === undefined) {
      throw new Error(`${operation.method} ${operation.path} missing x-koji-auth-required`);
    }
    if (!operation.operation['x-koji-capability']) {
      throw new Error(`${operation.method} ${operation.path} missing x-koji-capability`);
    }
    if (!Array.isArray(operation.operation['x-koji-errors'])) {
      throw new Error(`${operation.method} ${operation.path} missing x-koji-errors`);
    }
  }
  verifyRouteCoverage(document);
}

function getArg(name) {
  const index = process.argv.indexOf(name);
  if (index === -1) {
    return '';
  }
  return process.argv[index + 1] || '';
}

function verifyRouteCoverage(document) {
  const routeFile = readFileSync(join(repoRoot, 'internal/http/routes.go'), 'utf8');
  const registered = [...routeFile.matchAll(/mux\.HandleFunc\("([A-Z]+) ([^"]+)"/g)]
    .map((match) => `${match[1]} ${normalizeRoutePath(match[2])}`)
    .sort();
  const documented = operations(document)
    .map((operation) => `${operation.method.toUpperCase()} ${operation.path}`)
    .sort();
  const missing = registered.filter((route) => !documented.includes(route));
  const extra = documented.filter((route) => !registered.includes(route));
  if (missing.length > 0 || extra.length > 0) {
    throw new Error(`route coverage mismatch\nmissing: ${missing.join(', ') || 'none'}\nextra: ${extra.join(', ') || 'none'}`);
  }
}

function normalizeRoutePath(path) {
  return path.replace(/\{([^}]+)\}/g, '{$1}');
}

function operations(document) {
  const result = [];
  for (const [path, pathItem] of Object.entries(document.paths)) {
    for (const method of ['get', 'post', 'put', 'patch', 'delete']) {
      if (pathItem[method]) {
        result.push({ path, method, operation: pathItem[method] });
      }
    }
  }
  return result;
}

function apiReference(document, options = {}) {
  const endpointsLink = options.endpointsLink || 'Endpoints.md';
  const errorsLink = options.errorsLink || 'Errors.md';
  const lines = [
    '# Koji API Reference',
    '',
    'Generated from `docs/api/openapi.json`. Do not edit this file by hand.',
    '',
    `API version: \`${document.info.version}\``,
    '',
    '| Method | Path | Purpose | Authentication | Capability | Request | Response | Errors |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |'
  ];
  for (const operation of operations(document)) {
    lines.push(endpointRow(operation));
  }
  lines.push('', 'Related generated references:', '', `- [Endpoints](${endpointsLink})`, `- [Errors](${errorsLink})`);
  return `${lines.join('\n')}\n`;
}

function endpointsReference(document) {
  const lines = ['# Koji API Endpoints', '', 'Generated from `docs/api/openapi.json`.', ''];
  for (const operation of operations(document)) {
    lines.push(`## ${operation.method.toUpperCase()} ${operation.path}`);
    lines.push('');
    lines.push(operation.operation.description || operation.operation.summary || '');
    lines.push('');
    lines.push(`- Authentication: ${authText(operation.operation)}`);
    lines.push(`- Capability: \`${operation.operation['x-koji-capability']}\``);
    lines.push(`- CSRF required: ${operation.operation['x-koji-csrf-required'] ? 'yes' : 'no'}`);
    lines.push(`- Request: ${requestText(operation.operation)}`);
    lines.push(`- Response: ${responseText(operation.operation)}`);
    lines.push(`- Errors: ${errorText(operation.operation)}`);
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}

function errorsReference(document) {
  const codes = document.components.schemas.ErrorCode.enum;
  return `${[
    '# Koji API Errors',
    '',
    'Generated from `docs/api/openapi.json`.',
    '',
    'The current server error body contains a safe `error` field and an `X-Request-ID` response header. Client integrations may normalize these into the documented error codes.',
    '',
    '| Code | Meaning |',
    '| --- | --- |',
    ...codes.map((code) => `| \`${code}\` | ${humanize(code)} |`)
  ].join('\n')}\n`;
}

function endpointRow({ path, method, operation }) {
  return [
    method.toUpperCase(),
    `\`${path}\``,
    operation.summary || '',
    authText(operation),
    `\`${operation['x-koji-capability']}\``,
    requestText(operation),
    responseText(operation),
    errorText(operation)
  ].map(escapeCell).join(' | ').replace(/^/, '| ').replace(/$/, ' |');
}

function authText(operation) {
  return operation['x-koji-auth-required'] ? 'Required' : 'Public';
}

function requestText(operation) {
  if (!operation.requestBody) {
    return 'None';
  }
  return schemaName(operation.requestBody.$ref || operation.requestBody.content?.['application/json']?.schema?.$ref) || 'JSON body';
}

function responseText(operation) {
  const success = Object.entries(operation.responses).find(([status]) => status.startsWith('2'));
  return success ? responseName(success[1]) : 'None';
}

function responseName(response) {
  if (response.$ref) {
    return schemaName(response.$ref);
  }
  const schema = response.content?.['application/json']?.schema;
  return schemaName(schema?.$ref) || schema?.type || 'JSON';
}

function schemaName(ref) {
  return ref ? `\`${ref.split('/').at(-1)}\`` : '';
}

function errorText(operation) {
  return operation['x-koji-errors'].map((code) => `\`${code}\``).join(', ');
}

function escapeCell(value) {
  return String(value).replace(/\|/g, '\\|');
}

function humanize(value) {
  return value.replace(/_/g, ' ');
}

function toYAML(value) {
  return `${serializeYAML(value, 0)}\n`;
}

function serializeYAML(value, indent) {
  const pad = ' '.repeat(indent);
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return '[]';
    }
    return value.map((item) => `${pad}- ${serializeYAMLValue(item, indent + 2)}`).join('\n');
  }
  if (isObject(value)) {
    return Object.entries(value).map(([key, item]) => {
      if (Array.isArray(item) || isObject(item)) {
        const serialized = serializeYAML(item, indent + 2);
        return `${pad}${quoteKey(key)}:\n${serialized}`;
      }
      return `${pad}${quoteKey(key)}: ${serializeScalar(item)}`;
    }).join('\n');
  }
  return `${pad}${serializeScalar(value)}`;
}

function serializeYAMLValue(value, indent) {
  if (Array.isArray(value) || isObject(value)) {
    const serialized = serializeYAML(value, indent);
    return `\n${serialized}`;
  }
  return serializeScalar(value);
}

function serializeScalar(value) {
  if (value === null) {
    return 'null';
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  return JSON.stringify(value);
}

function quoteKey(key) {
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : JSON.stringify(key);
}

function isObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
